# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

# Trigger the workflow on any push to the main  bracnh and pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        # step 1 check out the code from repository
        - name: Check out code
          uses: actions/checkout@v4

        
        #step 2 set up python env
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: "3.8"

        # step 3 installl dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        # ste 4 run tests
        - name: Run tests
          run: pytest
